version: 0.2

phases:
  pre_build:
    commands:
      - echo Removing the Original WebPage Directory
      - rm -r webpage
      - bundle install
    finally:
      - echo WebPage Directory Removed
  build:
    commands:
      - echo Building the WebPage File
      - rake build 
    finally:
      - echo WebPage Directory Built
artifacts:
  type: zip
  files:
    - '**/*'