version: 0.2

phases:
  install:
    commands:
      - echo Installing Dependancies
      - gem 'middleman', '~>4.2.1'
      - gem 'middleman-syntax', '~> 3.0.0'
      - gem 'middleman-autoprefixer', '~> 2.7.0'
      - gem 'middleman-sprockets', '~> 4.1.0'
      - gem 'rouge', '~> 2.0.5'
      - gem 'redcarpet', '~> 3.4.0'
      - gem 'nokogiri', '~> 1.8.2'
      - gem 'middleman-gh-pages'
    finally:
      - echo Dependancies Installed
  pre_build:
    commands:
      - echo Removing the Original WebPage Directory
      - rm -f webpage
    finally:
      - echo WebPage Directory Removed
  build:
    commands:
      - echo Building the WebPage File
      - rake Build 
    finally:
      - echo WebPage Directory Built
artifacts:
  type: zip
  files:
    - '**/*'